# Generated by Django 6.0.6 on 2026-06-14 06:12

import apps.medicines.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicineCategory",
            fields=[
                (
                    "category_id",
                    apps.medicines.models.UUIDv7Field(
                        default=apps.medicines.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("category_description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicineManufacturer",
            fields=[
                (
                    "manufacturer_id",
                    apps.medicines.models.UUIDv7Field(
                        default=apps.medicines.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("manufacturer_name", models.CharField(max_length=100, unique=True)),
                ("manufacturer_description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "medicine_id",
                    apps.medicines.models.UUIDv7Field(
                        default=apps.medicines.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medicine_name", models.CharField(max_length=255)),
                ("medicine_description", models.TextField(blank=True, null=True)),
                ("medicine_stock", models.PositiveIntegerField(default=0)),
                (
                    "medicine_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "medicine_image",
                    models.ImageField(blank=True, null=True, upload_to="medicines/"),
                ),
                ("medicine_requires_prescription", models.BooleanField(default=False)),
                ("medicine_is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medicine_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medicines",
                        to="medicines.medicinecategory",
                    ),
                ),
                (
                    "medicine_manufacturer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medicines.medicinecategory",
                    ),
                ),
            ],
        ),
    ]
