# Generated by Django 6.0.6 on 2026-06-14 07:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="medicine_description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
