# Generated by Django 6.0.6 on 2026-07-01 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_medicine_medicine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.medicinemanufacturer'),
        ),
    ]
