# Generated by Django 4.2.16 on 2026-07-17 01:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_alter_medicine_medicine_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='active_ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='medicine',
            name='package_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='usage_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.medicinecategory'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.medicinemanufacturer'),
        ),
    ]
