# Generated by Django 4.2.16 on 2026-07-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_medicinereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='shipping_weight_grams',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated shipping weight in grams for one sellable unit, including its medicine packaging.', null=True),
        ),
    ]
