# Generated by Django 4.2.16 on 2026-07-23 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_alter_appointment_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterComorbidity',
            fields=[
                ('comorbidity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comorbidity_code', models.CharField(max_length=50, unique=True)),
                ('comorbidity_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_common', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_common', 'category', 'comorbidity_name'],
            },
        ),
        migrations.CreateModel(
            name='MasterSymptom',
            fields=[
                ('symptom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symptom_code', models.CharField(max_length=50, unique=True)),
                ('symptom_name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_common', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_common', 'category', 'symptom_name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('sent_to_pharmacy', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical_records.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('spo2', models.PositiveIntegerField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='appointments.appointment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentSymptom',
            fields=[
                ('appointment_symptom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symptom_code', models.CharField(max_length=50)),
                ('symptom_name', models.CharField(max_length=200)),
                ('severity_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='appointments.appointment')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_symptoms', to='medical_records.mastersymptom')),
            ],
            options={
                'ordering': ['symptom_name'],
                'unique_together': {('appointment', 'symptom')},
            },
        ),
        migrations.CreateModel(
            name='AppointmentComorbidity',
            fields=[
                ('appointment_comorbidity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comorbidity_code', models.CharField(max_length=50)),
                ('comorbidity_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comorbidities', to='appointments.appointment')),
                ('comorbidity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_comorbidities', to='medical_records.mastercomorbidity')),
            ],
            options={
                'ordering': ['comorbidity_name'],
                'unique_together': {('appointment', 'comorbidity')},
            },
        ),
    ]
