# Generated by Django 4.2.16 on 2026-07-23 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalMedicine',
            fields=[
                ('medicine_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medicine_code', models.CharField(max_length=50, unique=True)),
                ('medicine_name', models.CharField(max_length=150)),
                ('generic_name', models.CharField(blank=True, max_length=150)),
                ('dosage_form', models.CharField(blank=True, max_length=100)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('default_dosage', models.CharField(blank=True, max_length=100)),
                ('default_frequency', models.CharField(blank=True, max_length=100)),
                ('default_duration', models.CharField(blank=True, max_length=100)),
                ('default_instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['medicine_name'],
            },
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='hospital_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='medical_records.hospitalmedicine'),
        ),
    ]
