# Generated by Django 4.2.16 on 2026-07-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_hospitalmedicine_prescriptionitem_hospital_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalmedicine',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
