# Generated by Django 4.2.16 on 2026-07-30 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical_records', '0003_hospitalmedicine_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='assigned_nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_counter',
            field=models.CharField(blank=True, choices=[('counter_1', 'Counter 1'), ('counter_2', 'Counter 2'), ('counter_3', 'Counter 3')], max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pharmacy_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('assigned', 'Assigned'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
