# Generated by Django 4.2.16 on 2026-07-30 23:02

import apps.notifications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_alter_medicineorder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', apps.notifications.models.UUIDv7Field(default=apps.notifications.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('order_preparing', 'Order Preparing'), ('ready_for_pickup', 'Ready for Pickup'), ('dispatched', 'Picked Up'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery Failed'), ('returning', 'Returning'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], max_length=30)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('sms', 'SMS')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('destination', models.CharField(blank=True, help_text='Phone number, email address, or other delivery destination.', max_length=255)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medicine_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.medicineorder')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('medicine_order', 'event', 'channel'), name='unique_order_event_notification_channel'),
        ),
    ]
