# Generated by Django 6.0.6 on 2026-06-14 06:12

import apps.appointments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "appointment_id",
                    apps.appointments.models.UUIDv7Field(
                        default=apps.appointments.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[("home_visit", "Home Visit"), ("clinic", "Clinic")],
                        default="clinic",
                        max_length=15,
                    ),
                ),
                ("address", models.TextField(max_length=200)),
                ("notes", models.TextField(blank=True, max_length=255, null=True)),
                ("total_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
