# Generated by Django 4.2.16 on 2026-07-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
