# Generated by Django 6.0.6 on 2026-07-12 20:57

import apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='id',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user_address_id',
            field=apps.users.models.UUIDv7Field(default=apps.users.models.generate_uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
