# Generated by Django 6.0.6 on 2026-07-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_useraddress_city_remove_useraddress_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='province_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='province_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='ward_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='ward_namme',
            field=models.CharField(max_length=255),
        ),
    ]
