# Generated by Django 6.0.6 on 2026-07-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_useraddress_province_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='ward_namme',
            new_name='ward_name',
        ),
    ]
