# Generated by Django 6.0.6 on 2026-07-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_ward_namme_useraddress_ward_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='postcal_code',
            new_name='postal_code',
        ),
    ]
