# Generated by Django 6.0.6 on 2026-07-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_postcal_code_useraddress_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
