# Generated by Django 6.0.6 on 2026-07-14 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'OTHER')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='health_insurance_card',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Health insurance card must start with 2 uppercase letters followed by 13 digits (e.g. HS4030012345678).', regex='^[A-Z]{2}\\d{13}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
    ]
