# Generated by Django 4.2.16 on 2026-07-22 21:10

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[apps.users.validators.validate_profile_image]),
        ),
    ]
