# Generated by Django 4.2.16 on 2026-07-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Admin'), ('shipper', 'Shipper')], default='patient', max_length=10),
        ),
    ]
