import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, Box, CheckCircle2, MapPin, Phone, RotateCcw, Truck, XCircle } from 'lucide-react'
import { getShipperOrderDetail, updateShipperOrderStatus } from '../../services/orderService'
import styles from './ShipperOrderDetail.module.css'
const money=v=>`${Number(v||0).toLocaleString('vi-VN')} VND`
const label=s=>({ready_for_pickup:'Ready for pickup',dispatched:'Picked up',delivering:'Delivering',delivered:'Delivered',delivery_failed:'Delivery failed',returning:'Returning',returned:'Returned'}[s]||s)
export default function ShipperOrderDetail(){
 const {orderId}=useParams(); const [order,setOrder]=useState(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [reason,setReason]=useState(''); const [error,setError]=useState('')
 useEffect(()=>{(async()=>{try{const data=await getShipperOrderDetail(orderId);setOrder(data);setReason(data.delivery_failure_reason||'')}catch(e){setError(e.response?.data?.detail||'Could not load delivery.')}finally{setLoading(false)}})()},[orderId])
 const actions=useMemo(()=>({ready_for_pickup:[['dispatched','Confirm package pickup',Truck,'primary']],dispatched:[['delivering','Start delivery',Truck,'primary']],delivering:[['delivered','Confirm delivered',CheckCircle2,'success'],['delivery_failed','Report failed delivery',XCircle,'danger']],delivery_failed:[['returning','Start return',RotateCcw,'warning']],returning:[['returned','Confirm returned',RotateCcw,'warning']]}[order?.status]||[]),[order])
 async function update(status){if(status==='delivery_failed'&&!reason.trim()){setError('Please enter a delivery failure reason.');return}try{setBusy(true);setError('');setOrder(await updateShipperOrderStatus(orderId,status,reason.trim()))}catch(e){setError(e.response?.data?.detail||e.response?.data?.status?.[0]||'Could not update delivery.')}finally{setBusy(false)}}
 if(loading)return <main className={styles.page}><div className={styles.card}>Loading delivery...</div></main>
 if(!order)return <main className={styles.page}><div className={styles.card}>{error}</div></main>
 return <main className={styles.page}><Link className={styles.back} to="/shipper/dashboard"><ArrowLeft size={18}/>Back to dashboard</Link><section className={styles.header}><div><small>Order #{String(order.medicine_order_id).slice(0,8).toUpperCase()}</small><h1>{order.delivery_recipient_name}</h1></div><em className={styles[order.status]}>{label(order.status)}</em></section>{error&&<div className={styles.error}>{error}</div>}<div className={styles.layout}><section className={styles.main}><article className={styles.card}><h2>Recipient and address</h2><p><Phone size={19}/><a href={`tel:${order.delivery_phone}`}>{order.delivery_phone}</a></p><p><MapPin size={19}/>{order.delivery_address}</p><p><Box size={19}/>{order.package_weight_grams} g</p><a className={styles.map} target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(order.delivery_address)}`}>Open address in Maps</a></article><article className={styles.card}><h2>Medicine package</h2>{order.items?.map(i=><div className={styles.item} key={i.medicine_order_item_id}><span><b>{i.medicine_name}</b><small>Quantity: {i.quantity}</small></span><b>{money(Number(i.unit_price)*Number(i.quantity))}</b></div>)}</article>{order.status==='delivering'&&<article className={styles.card}><h2>Delivery problem</h2><textarea rows="4" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason is required for failed delivery"/></article>}</section><aside className={styles.card}><h2>Payment collection</h2><p className={styles.row}><span>Order total</span><b>{money(order.total_amount)}</b></p><p className={styles.row}><span>Method</span><b>{order.payment_method==='cash'?'Cash on delivery':order.payment_method||'Prepaid'}</b></p><p className={styles.row}><span>Status</span><b>{order.payment_status||'Not available'}</b></p>{order.payment_method==='cash'&&<div className={styles.cod}>Collect exactly <b>{money(order.total_amount)}</b> before confirming delivery.</div>}</aside></div>{actions.length>0&&<section className={styles.sticky}>{actions.map(([status,text,Icon,tone])=><button key={status} className={styles[tone]} disabled={busy} onClick={()=>update(status)}><Icon size={20}/>{busy?'Updating...':text}</button>)}</section>}</main>
}
