# Generated by Django 6.0.6 on 2026-06-14 06:12

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicineOrder",
            fields=[
                (
                    "medicine_order_id",
                    apps.orders.models.UUIDv7Field(
                        default=apps.orders.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("dispatched", "Dispatched"),
                            ("delivering", "Delivering"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivery_address", models.TextField()),
                ("ghtk_order_id", models.CharField(blank=True, max_length=100)),
                ("ghtk_tracking_url", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicineOrderItem",
            fields=[
                (
                    "medicine_order_item_id",
                    apps.orders.models.UUIDv7Field(
                        default=apps.orders.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
