# Generated by Django 4.2.16 on 2026-07-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_role'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicineorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivering_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_phone_2',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_province_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_province_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_recipient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_ward_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_ward_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='ghtk_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='ghtk_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='ghtk_status_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='medicine_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='package_weight_grams',
            field=models.PositiveIntegerField(default=500, help_text='Package weight sent to GHTK, in grams.'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='pickup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='preparing_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='returning_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='shipping_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='source_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_orders', to='users.useraddress'),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='ghtk_tracking_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='medicineorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Payment Confirmed'), ('preparing', 'Preparing Package'), ('ready_for_pickup', 'Ready for Pickup'), ('dispatched', 'Picked Up'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('delivery_failed', 'Delivery Failed'), ('returning', 'Returning'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
