# Generated by Django 4.2.16 on 2026-08-02 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_alter_medicineorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorder',
            name='assigned_shipper',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'shipper'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_medicine_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='delivery_failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicineorder',
            name='shipper_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
