# Generated by Django 4.2.16 on 2026-07-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_stage',
            field=models.CharField(choices=[('full', 'Full'), ('deposit', 'Deposit'), ('final', 'Final')], default='full', max_length=20),
        ),
    ]
