# Generated by Django 4.2.16 on 2026-07-25 13:59

import apps.payments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0006_appointment_deposit_amount_appointment_deposit_paid_and_more'),
        ('payments', '0002_payment_payment_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentFinalPaymentSession',
            fields=[
                ('session_id', apps.payments.models.UUIDv7Field(default=apps.payments.models.generate_uuid7, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=apps.payments.models.generate_final_payment_token, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_payment_sessions', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_final_payment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
