# Generated by Django 4.2.16 on 2026-07-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_appointmentfinalpaymentsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('vnpay', 'VNPAY'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('other', 'Other')], max_length=10),
        ),
    ]
