# Generated by Django 6.0.6 on 2026-06-14 07:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="bio",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
