# Generated by Django 6.0.6 on 2026-06-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_alter_doctor_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
