# Generated by Django 4.2.16 on 2026-07-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='visit_type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('home_visit', 'Home Visit')], default='clinic', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'day_of_week', 'visit_type', 'start_time', 'end_time')},
        ),
    ]
