# Generated by Django 4.2.16 on 2026-07-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_signatures/'),
        ),
    ]
